afterclass-io/afterclass.io

- src/common/components/Auth/AuthCard.tsx
- src/common/components/Auth/index.ts
- src/common/components/CoreLayout/CoreLayout.tsx
- src/common/components/CoreLayout/Sidebar.tsx
- src/common/components/CoreLayout/index.ts
- src/pages/login.tsx
This PR is for #8 
- CoreLayout
- created a pseudo `Sidebar` component in `/CoreLayout`
- added the `Sidebar` component to `CoreLayout.tsx`
- AuthCard
- created `AuthCard` component which allows changing of the card title through `title` prop. (default value has been set to 'Login') 
- allow overriding of card props using `forwardRef`
- input component left out
- button component left out
- sidebar content left for another issue
> feat: login layout

- .vscode/settings.json
- package.json
- src/common/components/Input/Input.theme.ts
- src/common/components/Input/Input.tsx
- src/common/components/Input/index.ts
- src/common/styles/components.scss
- src/common/styles/globals.scss
- src/pages/index.tsx
- tailwind.config.ts
- yarn.lock
- Import `tailwind-variants` library for managing tailwind classes and component states
- Create `Input` component matching figma design
- Includes example on index page
- Added vscode preferences
https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/4209fc36-6c9a-4455-82d6-173a8a2ec72c
> feat: input component

- src/common/components/Button/Button.theme.ts
- src/common/components/Button/Button.tsx
- src/common/components/Button/index.ts
- src/common/styles/components.scss
- src/common/tools/tailwind/themes/appTheme.ts
- src/common/tools/tailwind/themes/darkTheme.ts
- src/common/tools/tailwind/themes/lightTheme.ts
- src/pages/index.tsx
- Update theme colors to match latest Figma
- Add Button component
- Button component is polymorphic, and depending on `as = 'a' | 'button'` prop, it will render an anchor tag or NextLink comp or button tag. 
- If it includes `external` prop + `as = 'a'`, then the button will use `target='_blank'`
https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/ca251444-a10a-4e36-b728-33262b4d8bb4
Go to the preview link and the buttons should be at the bottom
> feat: button component

- src/app/components/page.tsx
- src/app/page.tsx
- src/common/components/Button/Button.theme.ts
- src/common/components/Button/Button.tsx
- src/common/components/CoreLayout/CoreLayout.tsx
- Added `ghost` variant (transparent bg)
- Added `loading` button state 
- Disabled onClick for `loading` and `disabled` button states
- Moved components from `app/page.tsx` to `app/components/page.tsx`
- Updated showcase of buttons
- Add comment on app index page to remove 'use client'
https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/5f266c96-8405-4e9d-9e1a-5ceeb67a1ef0
> feat: button ghost, disabled and loading states

- src/common/components/Textarea/Textarea.stories.tsx
- src/common/components/Textarea/Textarea.theme.ts
- src/common/components/Textarea/Textarea.tsx
- src/common/components/Textarea/index.ts
closes #33 
- \+ `Textarea` component
- \+ `Textarea` story
- left out the left / right icon/content component
- [Chromatic build review](https://www.chromatic.com/build?appId=65e66a97ccf98da794749891&number=22)
- [Storybooks on Chromatic](https://65e66a97ccf98da794749891-fipsuwccgh.chromatic.com)
> feat(ui): Textarea component

- src/common/components/Command/Command.theme.ts
- src/modules/reviews/Combobox.tsx
upgrading to cmdk v1.x ([`3684199`](https://github.com/AfterClass-io/afterclass.io-v2/pull/75/commits/36841994fbe679b565d38aa1a512536b926a4e83#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L33-R33)) broke `Command` component, which also impacted `Combobox` component
- [command component story @`main`](https://65e66a97ccf98da794749891-fipsuwccgh.chromatic.com/?path=/docs/common-command--docs)
- [combobox component story @`main`](https://65e66a97ccf98da794749891-fipsuwccgh.chromatic.com/?path=/docs/common-combobox--docs)
comment with elaborated solution
`https://github.com/shadcn-ui/ui/issues/2980#issuecomment-2029267475`
cmdk [v1.0.0 release notes](https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0):
> `Command.List` is now required (`CommandList` in `shadcn`)
> …
> fix: unintentional disabling of `Command` after upgrading cmdk to v1.x

- src/app/(school)/page.tsx
- src/server/api/root.ts
- src/server/api/routers/courses.ts
- src/server/api/routers/index.ts
closes #70
- add courses trpc router
- add `listByUni` public endpoint
- add `listByFaculty` public endpoint
- add `listByUni` protected endpoint
- add `listByFaculty` protected endpoint
- example implemenation
1. setup local dev env
a. run `docker compose up`
b. run `npx prisma migrate reset` to setup and seed the local db
2. navigate to `/`
3. sign in if needed
4. should see 10 courses from both private and protected endpoints. Private endpoint data should show more fields than public endpoint data
> feat(api): courses trpc router

- src/common/components/SchoolTag/SchoolTag.stories.tsx
- src/common/components/SchoolTag/SchoolTag.theme.ts
- src/common/components/SchoolTag/SchoolTag.tsx
- src/common/components/SchoolTag/index.ts
- src/common/components/Tag/Tag.theme.ts
- \+ `SchoolTag` Component
- use school icon
- update `<Tag/>` default y-padding to be double of original
- use `<Heading/>` component for school name
- [Chromatic build review](https://www.chromatic.com/build?appId=65e66a97ccf98da794749891&number=52)
- [Storybooks on Chromatic](https://65e66a97ccf98da794749891-ekswsrezhn.chromatic.com/)
> feat(ui): `SchoolTag` component

- src/common/components/PageTitle/PageTitle.stories.tsx
- src/common/components/PageTitle/PageTitle.theme.ts
- src/common/components/PageTitle/PageTitle.tsx
- src/common/components/PageTitle/index.ts
- \+ `PageTitle` Component
- use `<Heading/>` component for the main title
- accepts `children` as prop and passes to `<Heading/>`
- accepts left and right content to be placed beside `<Heading/>`
- [Chromatic build review](https://www.chromatic.com/build?appId=65e66a97ccf98da794749891&number=53)
- [Storybooks on Chromatic](https://65e66a97ccf98da794749891-slyaxyitoo.chromatic.com/)
> feat(ui): `PageTitle` component

- src/common/components/Tag/Tag.stories.tsx
- src/common/components/Tag/Tag.theme.ts
- src/common/components/Tag/Tag.tsx
- src/common/components/TagGroup/TagGroup.stories.tsx
- src/common/components/TagGroup/TagGroup.theme.ts
- src/common/components/TagGroup/TagGroup.tsx
- src/common/components/TagGroup/index.ts
- \+ `TagGroup` Component
- updated `<Tag/>` with a new `clickable` variant
- make `<Tag/>` as checkbox group for form input
- [Chromatic build review](https://www.chromatic.com/build?appId=65e66a97ccf98da794749891&number=63)
- [Storybooks on Chromatic](https://65e66a97ccf98da794749891-rkogcezuht.chromatic.com/)
> feat(ui): `TagGroup` component

- src/app/account/auth/confirm-signup/page.tsx
- src/app/account/auth/verify/page.tsx
- src/common/components/Auth/ConfirmSignUpNote.tsx
- src/common/components/Auth/VerificationEmailForm.tsx
- src/common/components/Auth/index.ts
- src/middleware.ts
- src/server/supabase.ts
Closes #12 
- add resend email feature
- add custom `confirm sign up` page where user can click on a button to verify their email
- redirect user to 404 page for any improper access to `verify` and `confirm-signup` page
1. Certain email providers may prefetch URL links from incoming emails as part of a security feature. In this case, the confirmation url link sent by Supabase to the use will be consumed instantly, which leads to a "Token has expired or is invalid" error. To mitigate this, we have chosen to create a custom email link to redirect the user to a custom  `confirm sign up page`. This implementation will require the user to actually clicks on the `confirm sign up` button to verify their identities.
Refer [supabase doc](https://supabase.com/docs/guides/auth/auth-email-templates) …
> feat: Email verification after sign up

- src/common/components/FilterToggleSection/FilterToggleSection.theme.ts
- src/common/components/FilterToggleSection/FilterToggleSectionItems/FilterToggleSectionItems.tsx
- src/common/components/FilterToggleSection/FilterToggleSectionSkeleton.tsx
- src/common/components/RatingSection/RatingSection.tsx
- src/common/components/Skeleton/Skeleton.theme.ts
- src/common/components/Skeleton/Skeleton.tsx
- src/common/components/Skeleton/index.ts
- src/common/components/StatItem/StatItem.tsx
- generic loading ui component - `<Skeleton/>`
- loading ui implementation for `<FilterToggleSectionSkeleton/>`, `<RatingSection/>` & `<StatItem/>`
> feat(ui): loading skeleton ui

- src/env.mjs
- src/server/supabase.ts
Current signup flow redirects user to the root `/`
Ever since change was made to let root `/` exempted from auth middleware at bced73beaba553bcd66df71d46b6b228ccfe4573, the redirect now pauses at root with the user not being signed in, requiring 1 extra click to be directed to login which is poor UX
Add `emailRedirectTo` option when `signUp` is called with email & password credentials, allowing redirect to be explicitly to `/account/auth/login` so the user will login after confirming their email
1. user click sign up
2. user input email + pwd & cfm pwd
3. user redirects to `/account/auth/verify` page to let user know that email is sent
4. user receives email
5. user clicks link on email & gets directed to `/account/auth/confirm-signup` page with a button that calls supabase api on click + …
> fix: explicit redirect to login instead of root

- src/app/(school)/(reviews)/@information/course/[code]/loading.tsx
- src/app/(school)/(reviews)/@information/course/[code]/page.tsx
- src/app/(school)/(reviews)/@information/default.tsx
- src/app/(school)/(reviews)/@information/page.tsx
- src/app/(school)/(reviews)/layout.tsx
- src/common/components/CustomIcon/ClipboardIcon.tsx
- src/common/components/CustomIcon/index.ts
- src/modules/reviews/InformationSection/InformationCard/InformationCard.theme.ts
- src/modules/reviews/InformationSection/InformationCard/InformationCard.tsx
- src/modules/reviews/InformationSection/InformationCard/InformationCardLoginButton.tsx
- src/modules/reviews/InformationSection/InformationCard/InformationCardSkeleton.tsx
- src/modules/reviews/InformationSection/InformationCard/InformationModal.tsx
- src/modules/reviews/InformationSection/InformationCard/index.ts
This PR addresses issue #88 and focuses on the implementation of the information component for the course page. The key features are as follows:
- Unauthenticated Users: They will see a truncated version of the information (up to 3 lines) along with a `login` link that redirects them to the login page.
- Authenticated Users: They will also see the truncated information, but with a `see more` link. Clicking this link will open a modal displaying the full course information.
For the Information Card, I have chosen a composition design by allowing the card component to accept `Log In Button` and `Modal` as children. This approach was adopted for several reasons:
- Minimise Prop Drilling: By passing these components as children, we avoid passing unnecessary props through multiple levels, …
> feat(UI): Course Page Info Card

- src/app/(school)/(reviews)/@information/course/[code]/loading.tsx
- src/app/(school)/(reviews)/@information/course/[code]/page.tsx
- src/modules/reviews/InformationSection/DetailCard/DetailCard.theme.ts
- src/modules/reviews/InformationSection/DetailCard/DetailCard.tsx
- src/modules/reviews/InformationSection/DetailCard/DetailCardSkeleton.tsx
- src/modules/reviews/InformationSection/DetailCard/index.ts
This PR addresses issue #88 and focuses on the implementation of the details component for the course page. This section will be displayed as it is to both authenticated and unauthenticated user.
Merging this PR closes #88 
- detail card components (including theme & skeleton)
- detail card implementation for course page (including loading state)
all reviews for selected course:https://afterclass-io-v2-git-feat-course-page-detail-section-afterclass.vercel.app/course/COR-IS1702
> feat(UI): Course Page Detail Card

- src/common/components/Modal/ModalContent/ModalContent.tsx
When a radix-ui modal is opened, it auto focuses the first thing in content. See `https://github.com/radix-ui/primitives/blob/main/packages/react/focus-scope/src/FocusScope.tsx`
Currently, the first element in content is the close button so it'll focus on that instead of the input element
This change is meant to fix that behavior and have the input component be focused on instead
- swap order of content children so that input component comes first
> fix: close button autofocus instead of input on open modal

- src/server/auth.ts
partially addresses #78 
This is done as a next step to #175 as user fields from prisma schema isn't exposed to the session object and hence, is not available for use like `session.user.username`
add user object to jwt token and get session object to update it's user field based on the token value
this jwt stores data representing the logged in user and some parts of the session data
- https://next-auth.js.org/configuration/callbacks#jwt-callback
- https://next-auth.js.org/configuration/callbacks#session-callback
login and should see username instead of blank name at the top right corner of profile header
> feat: expose user fields to session object

- src/common/components/SearchResult/SearchResult.stories.tsx
- src/common/components/SearchResult/SearchResultContent/SearchResultContent.tsx
- src/common/functions/searchCourse.ts
- src/common/functions/searchProf.ts
closes #162 
Previously, in #152 #161 , the search did not include querying for review statistics. This change adds that functionality to include the respective review statistics along with each search result.
Add an additional db query to fetch review statistics (prof count, course count, review count)
- use `Promise.all` to guarantee return structure and reduce wait time
1. head to home
2. press `/` to bring up search bar
3. search something simple, like `o` 
4. see results -> should have the relevant review statistics
> feat: search result includes review statistics

- src/common/components/ReviewModal/ReviewModal.tsx
- src/common/types/review.ts
- src/server/api/routers/reviews.ts
closes #164 
implement see more review and link to the respective professor/course page
added link
go to default reviews page and click see more reviews in the modal
> feat(ui): see more button links to respective page on review modal

- src/app/(school)/(reviews)/@filter/course/[code]/page.tsx
- src/app/(school)/(reviews)/@filter/professor/[slug]/page.tsx
- src/common/functions/searchCourse.ts
- src/common/functions/searchProf.ts
- src/server/api/routers/reviews.ts
closes #181 
When user want to filter a professor's review by course, the filter checkbox MUST reflect the correct statistics of how many review the user should expect when they filter by that course
allow review count api to accept both course code and prof slug to count more accurately by:
- \+ renamed count api
- \+ count api accepts optional prof slug and course code (if neither are given, then all review count is returned)
- \- removed previous countByX apis
1. search prof `vivien soon`
2. see that stats now accurately reflects 0 reviews for this prof for the mod `COR-IS1702`
> fix: inaccurate review statistics on filter

- src/server/api/routers/reviews.ts
closes #180
When we filter a course page for a particular prof, we expect to only see information / reviews of this prof for this course and nothing else.
The current behavior is to show all course reviews that are not tagged to a prof, along with that particular prof's reviews. Hence filtering for profs that dont have reviews still unexpectedly show reviews in the review section as those reviews are only written for courses and do not have a corresponsing `reviewedProfessor`
update reviews trpc procedure's primsa query when fetching for reviews belonging to this course when filtered by a particular prof
query for reviews with prof slug only when slug exists in the input param of the trpc procedure, otherwise, get all course reviews
1. head to `/course/COR-IS1702`
2. filter on profs with …
> fix: prof filter on course page not correctly filtering reviews

- src/modules/reviews/InformationSection/InformationCard/InformationCard.theme.ts
- src/modules/reviews/InformationSection/InformationCard/InformationModal.tsx
closes #148
This PR aims to fix the formatting of course's information data (bullets points appear on the same line etc) as described in issue 148
+ `whitespace-pre-wrap` css property for course's information modal
1. head to home page
2. search for a particular course (try `Computational Thinking`)
3. click on `see more` for information section
4. check if course information detail is formatted correctly
Correctly formatted information detail:
> fix: add whitespace pre wrap for modal body

- src/server/api/routers/reviews.ts
closes #ISSUE_NUMBER
By default, when loading to course page, we want to see all reviews related to that course in the review section, including reviews that are made for that course only, without being tied to a professor.
When we filter reviews for a particular prof on the course page, we want t othen see all reviews for that prof under this course.
A previous commit https://github.com/AfterClass-io/afterclass.io-v2/pull/193/commits/44bbc526cfa87b0a08d9a27f36986fe8c448668d at #193 broke this `see all reviews related to that course in the review section, including reviews that are made for that course only` behavior unintentionally.
Using the same data, without any change to the database, here is the before and after
(The newly added review with the `SELECT ...` text is a course-only …
> fix: course specific review not showing if where in clause is empty array

- src/common/components/Tag/Tag.tsx
- src/modules/submit/Combobox/Combobox.theme.ts
closes #189 
The reason why the tag is not reactive is due to `isActive` not having proper reference to the state as variables are not passed by reference
Updating the values to match fixes the problem
- update tag component `isActive` state variable
- (unrelated) update combobox select height to be `min-h-12` instead of a fixed `h-12`
1. go to `/submit`
2. select any course
3. click on review label tags
4. see it is now working
> fix(ui): review label tag on review form not reactive to clicks

- src/common/components/CoreLayout/CoreLayout.tsx
Currently, the moblie view is not scrollable. This PR fixes this bug
- add `overflow-y-scroll` on div below mobile header on CoreLayout
1. go to `/` 
2. open devtools
3. toggle on mobile view
4. try to scroll, should be able to scroll
5. toggle off mobile view
6. confirm desktop view is working well still
> fix(ui): mobile view not scrollable

- src/common/components/RatingSection/RatingSection.theme.ts
- src/common/components/RatingSection/RatingSection.tsx
- src/common/components/StatItem/StatItem.theme.ts
- src/common/components/StatItem/StatItem.tsx
closes #203
This PR focuses on the mobile responsiveness for rating section for both course and prof page (following AC's figma design)
+ mobile view for stat item
+ mobile view for rating section as a whole
+ fix desktop view for label alignment by adding `text-start`
1. go to any course / prof review page
2. open devtools
3. toggle on mobile view
4. try to scroll, should be able to scroll
5. toggle off mobile view
6. confirm desktop view is working well still
`md` view
`sm` view
> feat: mobile view for rating section

- src/common/components/CoreLayout/CoreLayout.tsx
- src/common/components/MobileHeader/MobileHeader.tsx
closes #218
changed to reflect the login status of the page for mobile view, replacing the login button in the header with a write a review button
1. removed login button on header
2. added a write a review button that links the user to the write review page
- changed CoreLayout.tsx to be async
- passed in logged in status as a prop to the MobileHeader component
- renders login or write a review button inside the MobileHeader accordingly
1. on mobile view, view the page without logging in, a "Login" button should be seen in the header
2. login and the button should be changed into a "Write a review" button
> fix: mobile view login button

- .env.example
- src/app/(school)/(reviews)/layout.tsx
- src/common/components/Sidebar/Sidebar.tsx
- src/env.mjs
closes #219 
This PR focuses on adding review submission and contribute buttons to the sidebar drawer on mobile view. These 2 items will not be visible on sidebar for any non-mobile view.
+ AC GitHub Link as env variable
+ New side menu items (Write a Review + AfterClass OSS)
+ New UI/UX for sidebar menu (added title for each section)
+ Change `href` on cta card on desktop view from actual link to env
1. go to AC's homepage at `/`
2. open devtools
3. toggle on mobile view
4. Side menu items for Write a Review + AfterClass OSS should be observed
5. Exit mobile view
6. Side menu items for Write a Review + AfterClass OSS should NOT be observed
`mobile`
`desktop`
> feat: mobile add review submission and contribute buttons to the sidebar drawer

- src/app/layout.tsx
closes #220 
currently, when user clicks on form input, the browser scales the viewport for the user on focus. this is an unintended and potentially annoying feature.
this pr disables that autozoom
- add `maximum-scale=1` to viewport meta
see https://stackoverflow.com/a/46254706
1. click on preview link on mobile
2. click login
3. click email / password field
4. should not see zooming
> feat(ui): disallow mobile to zoom on form input

- cypress/e2e/1-auth/reset_pwd.cy.js
- src/app/account/auth/forgot/page.tsx
- src/app/account/auth/signup/page.tsx
- src/modules/auth/components/ForgotPwdForm.tsx
- src/modules/auth/components/SignupForm.tsx
- src/modules/auth/components/SignupModalV1User.tsx
- src/modules/auth/components/index.ts
- src/modules/auth/functions/forgotPwdFormAction.ts
- src/modules/auth/functions/index.ts
- src/modules/auth/types/forgotPwdFormTypes.ts
- src/modules/auth/types/index.ts
The reason for this change is that many v1 users who have forgotten their password attempted to reset password on v2 site, despite instructions to create an account on v2 instead.
This has led to confusion by the user as resetting password on v2 wont work since user is manageed with supabase auth and v1 users haven't yet exist on supabase auth.
This change will redirect user to sign up page with a Modal explaining that they should create an account instead, when user attempts to reset a password for a v1 account.
- reset password prompt now redirects to signup page if email given is a v1 account
1. user submits reset request with an email
2. check if email exists. if no: show error message to user that email doesnt exist
3. check if `deprecatedPasswordDigest` column is populated. if no: …
> feat(auth): redirect to acct creation on v1 acct pwd reset

- src/common/providers/EdgeConfig/EdgeConfigProvider.tsx
closes #ISSUE_NUMBER
- add fallback to use local json config if dev doesnt' have the correct edge config env token, so development workflow isn't blocked
- app should work locally with /without or correct/incorrect `EDGE_CONFIG` variable in `.env` file
> feat: local config fallback for invalid edge config

- cypress/e2e/2-reviews/course.cy.js
- cypress/e2e/2-reviews/professor.cy.js
- src/app/(school)/(reviews)/@rating/course/[code]/page.tsx
- src/app/(school)/(reviews)/@rating/professor/[slug]/page.tsx
- src/app/(school)/(reviews)/@reviews/course/[code]/opengraph-image.tsx
- src/app/(school)/(reviews)/@reviews/professor/[slug]/opengraph-image.tsx
- src/common/functions/calculateAverage.ts
- src/common/functions/formatPercentage.ts
- src/modules/reviews/components/RatingSection/RatingSection.stories.tsx
- src/modules/reviews/components/ReviewItemLoader/ReviewItemLoader.tsx
- src/modules/reviews/functions/calculateRatingItems.ts
- src/server/api/routers/reviews.ts
closes #347
- use updated metadata query `getMetadataForCourse` & `getMetadataForProf`
- review section now shows a message if there are no reviews
> fix: prof and course review section inaccurate metadata

- .eslintrc.cjs
- tsconfig.json
Added some configuration to address ESLint diagnostics issues.
When the contributor use personal config within their system, their settings could possibly leak into project's ESLint, and this may introduce some changes that may conflict with the repository's.
Error from ESLint diagnostics:
```
Diagnostics:
1. eslint: (node:86725) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "../../../.eslintrc.json")
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Another errors that was found with ESLint diagnostics:
```
Diagnostics:
1. eslint: Parsing error: …
```
> chore(devconfig): ESLint & TSConfig issues

- src/env.ts
- src/modules/auth/components/GoogleSignInButton.tsx
- src/modules/auth/components/LoginForm.tsx
- src/server/auth/config.ts
previously we've introduced a change on #383 to allow google oauth
with further inspection, we found 2 main issues:
1. `session.user.id` field (returned when calling `auth()` no longer matches `db.users.id` if auth method is google oauth
2. if any step during auth fails, user is redirected to `/account/auth/error` which doesnt exist
- if auth fails, redirect to `/account/auth/login` with the `?error=` param
- display toast message on login page if auth fails
- load db user on `session.user` during jwt callback if auth method was google auth
(this is intentionally not done on the session callback as we dont want to initiate a db call everytime a session is checked. see https://authjs.dev/reference/core#session)
> fix: auth display error on failure & session user to match db user on google auth

- src/modules/reviews/components/ReviewItem/ReviewFooter/ReviewFooter.tsx
- src/server/ecfg/config.json
- src/server/ecfg/config.ts
following up to #405, we'd ideally want to put that new feature behind a feature flag before releasing it to the public internet, to protect against unforseen issues in production, with easy rollbacks
- update `config.json` with the latest deployed ecfg json
- add a new `enableReviewReactions` bool field on ecfg
- hide review reaction functionality if `enableReviewReactions` is `false`
> feat(flags): use feature flag for review reactions

- src/modules/reviews/components/ReviewItem/ReviewVoteGroup/ReviewVoteGroup.tsx
- src/server/api/hackVotes/voteOrUnvote/index.ts
- src/server/api/reviewVotes/voteOrUnvote/index.ts
Directly sending a POST request to `https://www.afterclass.io/api/trpc/hackVotes.voteOrUnvote?batch=1` with appropriate headers allows vote weight to be modified.
Clamped vote weight to 0 or 1 in server side, before db upsert
Send a cURL request
```bash
curl --location 'http://localhost:3000/api/trpc/hackVotes.voteOrUnvote?batch=1' \
--header 'Content-Type: application/json' \
--header 'Cookie: <COOKIE_HERE>' \
--data '{
"0": {
"json": {
"hackSubmissionId": "c276d7a9-a9d9-4e43-b280-35f0bd3e97a3",
"weight": 100
}
}
}'
```
(I couldn't actually test this locally, but the idea works on prod. I used postman to sync my cookies and it sent the new weights in. To test the clamp function, I updated the weight value in submission.tsx)
Vote should be capped at 1
> fix(voting): clamp weight values server side

- src/common/components/vote-group.tsx
- src/modules/reviews/components/ReviewItem/ReviewVoteGroup/ReviewVoteGroup.tsx
- src/modules/reviews/hooks/useOptimisticReaction.ts
- src/server/api/reviewReactions/upsert/index.ts
Improve user experience in edge cases where user spam clicks reactions or upvotes. Debouncing reduces load on server.
Optimistic update provides instant feedback on users' actions. Strange bug with spamming upvote, number increases more than +1. Eg. start state votes 10, spam upvote can increase number greater than 11.
Minor UX improvement to NumberFlow component with negative votes. Number spins when vote from 0 to -1. Set [trend](https://number-flow.barvian.me/#props) prop in component to fix.
Similar logic between vote and reaction debouncing. Reaction uses a custom hook, votes was built-in the component.
Run locally and spam click reactions and upvotes/downvotes and see network tab doesn't flood requests to the BE. UI changes correctly and optimistically.
> feat(ui): debounce review reactions and upvotes

- prisma/migrations/20250621171745_add_warn_inaccuracy_field_classes_table/migration.sql
- prisma/schema.prisma
BOSS sometimes [lazily list](https://boss.intranet.smu.edu.sg/ClassDetails.aspx?SelectedAcadTerm=2110&SelectedClassNumber=2462) courses (aka classes) that has multiple professors into 1 class schedule, and leave the rest of the class schedules with no professors
the effect being, we'll never know which professor would teach which schedule
to combat this, we will track when we encounter such ambiguity and prompt our users that the data might be inaccurate
> feat(db): add warn_inaccuracy field to classes table

- src/modules/bidding/components/BidPredictionCard.stories.tsx
- src/modules/bidding/components/ClassCard.stories.tsx
BidPredictionCard and ClassCard did not have corresponding files for storybook.
Added .stories.tsx files for both components
Added .stories.tsx files for both components
Components now accessible through storybook under the Bid Analytics section
- [✅] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [✅] I have tested the changes
- [✅] _(where applicable)_ I have added tests to cover my changes
- [✅] _(where applicable)_ I have updated the documentation accordingly
> chore: create storybook files for BidPredictionCard and ClassCard
