.env.example, package.json, prisma/schema.prisma, src/common/components/CoreLayout/CoreLayout.tsx, src/env.mjs, src/pages/api/auth/[...nextauth].ts, src/pages/index.tsx, src/server/auth.ts, src/server/supabase.ts, yarn.lock
This change partially addresses #2, Login Flow in particular.
Minimally, the Auth Service (or function) should be able to:
1. Validate user's login credentials
2. Verify that user is a student from a supported school by verifying their `.edu` email address
3. Allow for password reset _(not required if password is not needed, if say, we used a third-party provider)_
In this case, NextAuth's [CredentialsProvider](https://next-auth.js.org/providers/credentials) is intentionally used instead of a popular provider like NextAuth's [GoogleProvider](https://next-auth.js.org/providers/google) as it is not guaranteed that all our user's school email accounts would be registered with a working Google account or with whichever would be our third-party identity provider of choice.
I've made a …
=> feat: NextAuth Supabase login

src/app/components/page.tsx, src/common/components/Tag/Tag.theme.ts, src/common/components/Tag/Tag.tsx, src/common/components/Tag/index.ts
closes #50
- \+ `Tag` component with variants
=> feat(ui): tag component

src/app/(school)/page.tsx, src/server/api/root.ts, src/server/api/routers/index.ts, src/server/api/routers/reviews.ts
> ‼️ NOTE: This PR will be rebased to main after #75 is merged. (do not merge before #75!)
closes #6, closes #71
- add reviews trpc router
- add `getAll` reviews protected endpoint
- add `create` reviews protected endpoint
1. setup local dev env
a. run `docker compose up`
b. run `npx prisma migrate reset` to setup and seed the local db
2. navigate to `/`
3. sign in if needed
4. should see 10 reviews
=> feat(api): reviews trpc router

package.json, src/common/components/ToggleGroup/ToggleGroup.stories.tsx, src/common/components/ToggleGroup/ToggleGroup.theme.ts, src/common/components/ToggleGroup/ToggleGroup.tsx, yarn.lock
> ‼️ NOTE: This PR will be rebased to main after #76 is merged. (do not merge before #76!)
closes #36 
- \+ "@radix-ui/react-toggle-group" npm dep
- \+ `ToggleGroup` component
- \+ `ToggleGroup` story
- [Chromatic build review](https://www.chromatic.com/build?appId=65e66a97ccf98da794749891&number=21)
- [Storybooks on Chromatic](https://65e66a97ccf98da794749891-pkwemptqmn.chromatic.com)
=> feat(ui): ToggleGroup component

src/common/components/Checkbox/Checkbox.tsx
closes #97 
references:
- `https://github.com/storybookjs/storybook/discussions/21525#discussioncomment-6017059`
- `https://github.com/storybookjs/storybook/issues/15137`
=> fix(#97): checkbox storybook not rendering correctly on local dev

prisma/data/10_review_labels.json, prisma/data/9_reviews.json, prisma/migrations/20240519084041_make_course_code_unique/migration.sql, prisma/migrations/20240523164350_init/migration.sql, prisma/schema.prisma, src/app/(school)/(reviews)/@filter/course/[code]/loading.tsx, src/app/(school)/(reviews)/@filter/course/[code]/page.tsx, src/app/(school)/(reviews)/@header/course/[code]/loading.tsx, src/app/(school)/(reviews)/@header/course/[code]/page.tsx, src/app/(school)/(reviews)/@rating/course/[code]/loading.tsx, src/app/(school)/(reviews)/@rating/course/[code]/page.tsx, src/app/(school)/(reviews)/course/[code]/loading.tsx, src/app/(school)/(reviews)/course/[code]/page.tsx, src/app/(school)/(reviews)/default.tsx, src/common/functions/calculateAverage.ts, src/common/functions/index.ts, src/middleware.ts, src/modules/reviews/functions/calculateRatingItems.ts, src/server/api/routers/courses.ts, src/server/api/routers/professors.ts, src/server/api/routers/reviews.ts
This PR focuses on the integration for course page. Few important functionalities include:
- Able to view all reviews for a selected course (including reviews for a professor which is related to a course)
- Able to filter reviews based on selected professor(s)
For course information component, it will be covered in another PR to keep this PR small and easy to be reviewed
- new review with id `s0b1ee9e-6164-4565-890d-45d844593e63` under `review.json`
- change 2 reviews's `reviewedProfessorId` field to `null` to reflect course reviews
- new review with course and professor labels under `review_labels.json`
- updated schema for course table to make course code unique
- updated `middleware.ts` to apply middleware to `course` route
- extracted rating calculations part to 2 functions (refer …
=> feat(UI): Course Page Integration

.github/release.yml, .github/workflows/changelog.yml
Closes #130. Find the details at #153
=> feat: automatically generate release notes with changelog

src/app/(school)/layout.tsx
partially addresses #78 
simplify user login flow to login from header
add login button to header
header component
- [ X] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ X] I have tested the changes
=> update header to use login button

src/common/components/Sidebar/Sidebar.tsx
closes #172 
Marketplace and deals are not planned to be worked on anytime soon, so to reduce confusion for users, I have removed these options from the sidebar.
Removed marketplace and deals from sidebar.
removed marketplace and deals from sidebar items at [src/common/components/Sidebar/Sidebar.tsx]
1. Open the application and navigate to the sidebar.
2 .Confirm that the items previously listed (Marketplace, deals) are no longer visible.
- [ ✔] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ ✔] I have tested the changes
=> removed marketplace and deals from sidebar items

src/app/(school)/layout.tsx
partially addresses #78 
added user profile component to header
copied profile reviewer as a raw component to school layout
login and see top right profile
=> added user profile component

src/common/components/ReviewItem/ReviewItem.tsx, src/common/components/ReviewModal/ReviewModal.tsx
closes #163
Hide the see more reviews on the professor page as it is not needed.
Hide the see more reviews button on the professor page
put conditional checking for professor
Click on course and professor review.
=> refactor: hide see more reviews

src/common/components/ReviewModal/ReviewModal.theme.ts, src/common/components/ReviewModal/ReviewModal.tsx
closes #207 
- add responsive variant `size` on review modal theme
- add `<Modal.Footer/>` component to the review modal
1. open a review modal
2. open devtools
3. make viewport responsive
4. check modal changes when viewport changes
=> feat(ui): review modal responsive mobile viewport

src/app/account/auth/confirm-signup/page.tsx, src/app/account/auth/layout.tsx, src/app/account/auth/login/page.tsx, src/app/account/auth/reset-password/page.tsx, src/app/account/auth/signup/page.tsx, src/app/account/auth/verify/page.tsx, src/common/components/Auth/AuthCard.tsx, src/common/components/Auth/ConfirmSignUpNote.tsx, src/common/components/Auth/LoginForm.tsx, src/common/components/Auth/SignupForm.tsx, src/common/components/Button/Button.theme.ts, src/common/components/Button/Button.tsx, src/common/components/CoreLayout/CoreLayout.tsx, src/common/components/Input/Input.tsx, src/common/components/Label/Label.tsx, src/common/components/MobileHeader/MobileHeader.tsx
closes #205 
- update auth pages to be responsive
- update corelayout to make mobile pages scrollable
- fix button responsiveness
- update input and label to be responsive by default
=> feat(ui): mobile view for auth flows

src/app/(school)/(reviews)/layout.tsx, src/common/components/CtaCard/CtaCard.tsx, src/common/components/CustomIcon/GithubIcon.tsx, src/common/components/CustomIcon/index.ts
closes #200
added props for icons in cta component
updated opacity for edit icon
visit the homepage/any course page
=> chore: allow passing icons as props to ctacard

src/app/(school)/(reviews)/@header/course/[code]/page.tsx, src/app/(school)/(reviews)/@header/professor/[slug]/page.tsx
changed the usage of `<Tag>` and `<SchoolIcon>` to just use the `<SchoolTag>` component instead
=> fix: removed the Tag and SchoolIcon to become SchoolTag

next.config.js, src/app/layout.tsx, src/common/components/CustomIcon/StatisticsTableIcon.tsx, src/common/components/CustomIcon/index.ts, src/common/components/Sidebar/Sidebar.tsx
docs:
- https://nextjs.org/docs/app/building-your-application/deploying/multi-zones
- https://nextjs.org/docs/app/api-reference/next-config-js/rewrites
- `https://github.com/vercel/next.js/blob/canary/examples/with-zones`
=> fix: multizonal hosting of umami public share url

src/modules/submit/components/ReviewForm/ReviewForm.tsx
see https://stackoverflow.com/a/75008835
=> fix: aborterror fetch is aborted

bun.lock, package.json
- `https://github.com/vercel/next.js/issues/48748`
=> fix: next dev slow compilation - split tailwindcss process

src/app/themes/page.tsx, src/common/tools/tailwind/functions/flattenObject.ts, src/modules/home/components/AppSidebar/AppSidebar.tsx
=> feat(ui): dev-only themes preview page

package.json, src/app/(school)/(reviews)/@rating/course/[code]/page.tsx, src/app/(school)/(reviews)/@rating/professor/[slug]/page.tsx, src/common/components/CustomIcon/HeartIcon.tsx, src/common/components/Modal/Modal.stories.tsx, src/common/components/Modal/Modal.tsx, src/common/components/Modal/ModalDescription/ModalDescription.tsx, src/common/components/Modal/ModalDescription/index.ts, src/common/components/Modal/ModalHeader/ModalHeader.tsx, src/common/components/Modal/ModalTitle/ModalTitle.tsx, src/common/components/Modal/ModalTitle/index.ts, src/modules/reviews/components/ReviewItem/ReviewBody/ReviewBody.tsx, src/modules/reviews/components/ReviewItem/ReviewItem.theme.ts, src/modules/reviews/components/ReviewItem/ReviewLabelGroup/ReviewLabelGroup.tsx, src/modules/reviews/components/ReviewItem/ReviewLabelGroup/index.ts, src/modules/reviews/components/ReviewItem/ReviewModal/ReviewModal.tsx, src/modules/reviews/components/ReviewItem/ReviewRatingGroup/ReviewRatingGroup.tsx, src/modules/reviews/components/ReviewItem/ReviewRatingGroup/index.ts
=> feat(ui): show more details on review items

src/common/components/CoreLayout/CoreLayout.tsx, src/common/components/CoreLayout/CoreLayoutHeader/CoreLayoutHeader.tsx, src/common/components/CoreLayout/CoreLayoutLoginButton/CoreLayoutLoginButton.tsx, src/common/components/CoreLayout/CoreLayoutLoginButton/index.ts, src/common/components/Progress/ProgressLink/ProgressLink.tsx
deployment - https://afterclass-io-v2-p0szfro1h-afterclass.vercel.app/
=> fix: progresslink component fails to push routes if href is urlobject

.github/workflows/ci-edge-config.yml, src/modules/reviews/components/ReviewItem/ReviewLikeButton/ReviewLikeButton.tsx, src/modules/reviews/components/ReviewItem/ReviewModal/ReviewModal.tsx, src/modules/reviews/components/ReviewItem/ReviewShareButton/ReviewShareButton.tsx, src/modules/reviews/components/ReviewItemViewEventTracker/ReviewItemViewEventTracker.tsx, src/modules/reviews/components/ReviewSection/ReviewSectionHeaderSortGroup.tsx, src/modules/reviews/components/ReviewSection/ReviewSectionListFilter.tsx, src/server/ecfg/config.json, src/server/ecfg/config.ts
=> feat: wrap review events tracking behind feature flags on edge config

bun.lock, package.json, src/common/components/HoverCard/HoverCard.stories.tsx, src/common/components/HoverCard/HoverCard.theme.ts, src/common/components/HoverCard/HoverCard.tsx, src/common/components/HoverCard/index.ts
- https://ui.shadcn.com/docs/components/hover-card
=> feat(ui): add hovercard shadcn component

src/common/components/CoreLayout/CoreLayout.tsx, src/common/components/ScrollToTopButton/ScrollToTopButton.tsx, src/common/hooks/useIntersectionObserver.ts
closes #188 
feature: #188 
add useIntersectionObserver hook
add scrollToTop button
add scrollToTop div
scroll down and click scroll to top button
- [ x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ x ] I have tested the changes
=> feat: jump to top button

src/app/(school)/(reviews)/@information/course/[code]/page.tsx, src/modules/reviews/components/InformationSection/DetailCard/DetailCard.tsx, src/server/api/classes/constants.ts, src/server/api/classes/getAllByCourseId/index.ts, src/server/api/classes/router.ts, src/server/api/courses/getByCourseCode/index.ts, src/server/api/root.ts
closes #416 
#416 
add classRouter
add link based off courseOutlineUrl
go to course and click on link
=> feat(ui): add course outline url to course detail card

src/modules/home/components/AppSidebar/AppSidebar.tsx
=> feat(ui): make statistics sidebar anchor an external link

bun.lock, package.json, src/app/(school)/(reviews)/@filter/course/[code]/page.tsx, src/app/(school)/(reviews)/@filter/professor/[slug]/page.tsx, src/app/(school)/(reviews)/@header/course/[code]/page.tsx, src/app/(school)/(reviews)/@header/professor/[slug]/page.tsx, src/app/(school)/(reviews)/@information/course/[code]/page.tsx, src/app/(school)/(reviews)/@rating/course/[code]/page.tsx, src/app/(school)/(reviews)/@rating/professor/[slug]/page.tsx, src/app/(school)/(reviews)/@reviews/course/[code]/page.tsx, src/app/(school)/(reviews)/@reviews/professor/[slug]/page.tsx, src/app/(school)/search/page.tsx, src/app/account/auth/confirm-account/page.tsx, src/app/account/auth/signup/page.tsx, src/app/account/auth/verify/page.tsx, src/common/components/Button/Button.tsx, src/common/components/CoreLayout/CoreLayout.tsx, src/common/components/CtaCard/CtaCard.tsx, src/common/components/Modal/ModalProvider.tsx, src/common/components/ScrollToTopButton/index.ts, src/common/components/Tag/Tag.tsx, src/common/hooks/useTransitionMount.ts, src/common/tools/trpc/server.ts, src/common/types/system.ts, src/modules/reviews/components/ReviewItem/ReviewModal/ReviewModal.tsx
closes #400 
see https://nextjs.org/docs/app/getting-started/upgrading
=> chore(deps): bump next to v15, react to v19

prisma/migrations/20250622034247_update_classes_prof_nullable/migration.sql, prisma/schema.prisma, src/server/api/courses/getByProfSlug/index.ts, src/server/api/professors/getByCourseCode/index.ts
Some classes listed on BOSS do not have professors listed along side the class schedule.
Due to this, we're making professor a nullable reference on classes.
=> feat(db): update classes prof_id field to nullable

prisma/migrations/20250628104945_add_user_bid_table_schema/migration.sql, prisma/migrations/20250628105349_rename_bid_prediction_table/migration.sql, prisma/schema.prisma
=> feat(db): add user bid table schema

prisma/migrations/20250706191357_update_safety_factor_table/migration.sql, prisma/schema.prisma
=> feat(db): update safety table schema

DEVELOPMENT.md
More details for setting up dev environment.
Added instructions for connecting a blank Supabase project for the development database.
Added note on running prisma/seed.ts if database seeding doesn't happen automatically/
N/A
- [✔] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
=> Docs: Supabase postgres development tips
